config/routes.rb
Rails.application.routes.draw do

  get "guanli" => "cookies#new", :as => "guanli"
  get "logout" => "cookies#destroy", :as => "logout"
  get "zhuce" => "users#new", :as => "zhuce"

  root "pages#index"
 
  resources :users
  resources :cookies
  resources :pages

  namespace :admin do
    resources :pages
  end

  namespace :admin do
    resources :galleries
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # users.password_hash in the database is a :string
  include BCrypt

  has_secure_password

  # attr_accessor :password
  
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  before_create { generate_token(:auth_token) } 

  before_save :encrypt_password

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end


  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  # def password
  #   @password ||= Password.new(password_hash)
  # end

  # def password=(new_password)
  #   @password = Password.create(new_password)
  #   self.password_hash = @password
  # end
end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < ApplicationController
  before_action :authorize
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
    @page
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to admin_pages_path, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to admin_pages_path, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to admin_pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.fetch(:page, {}).permit(:title, :body)
    end

    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :current_user

  def current_user
    @current_user ||= User.find_by_auth_token!(cookies[:auth_token]) if cookies[:auth_token]
  end
  # helper_method :current_user

  def authorize
    redirect_to guanli_url, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/cookies_controller.rb
class CookiesController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      cookies.permanent[:auth_token] = user.auth_token
      redirect_to admin_pages_path, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    cookies.delete(:auth_token)
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show]

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
    @page
  end





  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authorize, only: [:new, :create]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, :notice => "Thank you for Signed up!"
    else
      render "new"
    end
  end

  private
  
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/helpers/admin/pages_helper.rb
module Admin::PagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cookies_helper.rb
module CookiesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/pages/_form.html.haml
= form_for([:admin, page], :url => (admin_page_path(@page) if @page.persisted?) ) do |f|
  - if page.errors.any?
    #error_explanation
      %h2
        = pluralize(page.errors.count, "error")
        prohibited this page from being saved:
      %ul
        - page.errors.full_messages.each do |message|
          %li= message

  = f.label :Title
  = f.text_field :title
  %br
  = f.label :Body
  = f.text_field :body
  %br
  .actions
    = f.submit

app/views/admin/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', admin_pages_path %>

app/views/admin/pages/index.html.haml
%p#notice= notice
%h1 Pages
%table
  %thead
    %tr
      %th{:colspan => "3"}
  %tbody
    - @pages.each do |page|
      %tr
        %td= link_to "#{page.title}", admin_page_path(page)
        %td= link_to 'Edit', edit_admin_page_path(page)
        %td= link_to 'Destroy', admin_page_path(page), method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Page', new_admin_page_path

%p
  = params.inspect

app/views/admin/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Back', admin_pages_path %>

app/views/cookies/new.html.haml
= form_tag cookies_path do
  %p
    = label_tag :email
    = text_field_tag :email, params[:email]
  %p
    = label_tag :password
    = password_field_tag :password
  %p.button
    = submit_tag "Log in"
  

app/views/pages/index.html.haml
%p#notice= notice
%h1 Pages
%table
  %thead
    %tr
      %th{:colspan => "3"}
  %tbody
    - @pages.each do |page|
      %tr
        %td= link_to 'Show', page
        %td= link_to 'Edit', edit_page_path(page)
        %td= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Page', new_page_path

%p
  = params.inspect

app/views/pages/show.html.haml
%p#notice= notice



%h3= @page.title
= @page.body

%p
  = params.inspect

app/views/users/login.html.erb
<h1>User#login</h1>
<p>Find me in app/views/user/login.html.erb</p>

app/views/users/new.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    .error_messages
      %h2 Form is invalid
      %ul
        - for message in @user.errors.full_messages
          %li= message

  %p
    = f.label :email
    = f.text_field :email
  %p
    = f.label :password
    = f.password_field :password
  %p
    = f.label :password_confirmation
    = f.password_field :password_confirmation

  = f.submit